FROM docker.io/library/ruby:4.0.1-slim

# Install system dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential curl git libyaml-dev pkg-config libvips sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install Node.js 22
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install --no-install-recommends -y nodejs && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /rails

EXPOSE 3000 3036
